Repository fga-eps-mds/2024.1-PrintGo-PrinterService, pull requests merged in 2024-08, with the labels that each got.

#36 [Feature] - Registro Manual de Contadores de Impressão
  docker-compose.yml
  docker/Dockerfile.development
  docker/Dockerfile.production
  package.json
  prisma/migrations/20240815232229_initial/migration.sql
  prisma/schema.prisma
  src/controllers/Impressora.controller.ts
  src/controllers/validator/Impressora.validator.ts
  src/repository/Impressora.repository.ts
  src/routes/impressora.route.ts
  src/types/Impressora.type.ts
  tests/controllers/Impressora.controller.spec.ts
  tests/repositories/Impressora.repository.spec.ts
  tests/validators/Impressora.validator.spec.ts
Labels: feature

#38 Fix/dockerfile prod
  docker/Dockerfile.production
  package.json
  src/types/Contador.type.ts
Labels: EPS, devops

#40 [Feature] - Registro Automático de Impressões
  docker-compose.yml
  package-lock.json
  package.json
  prisma/migrations/20240819213222_cria_rotina_snmp/migration.sql
  prisma/schema.prisma
  src/controllers/Padrao.controller.ts
  src/controllers/RotinaSnmp.controller.ts
  src/controllers/validator/Padrao.validator.ts
  src/controllers/validator/RotinaSnmp.validator.ts
  src/repository/Impressora.repository.ts
  src/repository/Padrao.repository.ts
  src/repository/RotinaSnmp.repository.ts
  src/routes/rotinaSnmp.route.ts
  src/scripts/updatePrinterCounts.js
  src/server.ts
  src/snmp/cronJobs.ts
  src/snmp/snmpUtils.ts
  src/testaSnmp.js
  src/types/RotinaSnmp.type.ts
  src/utils/utils.ts
  tests/controllers/RotinaSnmp.controller.test.ts
  tests/repositories/Impressora.repository.spec.ts
  tests/snmp/snmpUtils.spec.ts
  tests/utils/utils.spec.ts
Labels: feature

#43 hotfix[Tests]: corrigindo math.random.
  package-lock.json
  package.json
  src/usecases/report/generate.report.ts
Labels: MDS, hotfix

#39 Release 2
  .github/workflows/metrics.yml
  docker-compose.yml
  docker/Dockerfile.development
  docker/Dockerfile.production
  package-lock.json
  package.json
  prisma/migrations/20240815232229_initial/migration.sql
  prisma/migrations/20240819213222_cria_rotina_snmp/migration.sql
  prisma/schema.prisma
  src/controllers/Impressora.controller.ts
  src/controllers/Locadora.controller.ts
  src/controllers/Padrao.controller.ts
  src/controllers/Report.controller.ts
  src/controllers/RotinaSnmp.controller.ts
  src/controllers/validator/Impressora.validator.ts
  src/controllers/validator/Padrao.validator.ts
  src/controllers/validator/RotinaSnmp.validator.ts
  src/repository/Impressora.repository.ts
  src/repository/Locadora.repository.ts
  src/repository/Padrao.repository.ts
  src/repository/Report.repository.ts
  src/repository/RotinaSnmp.repository.ts
  src/routes/impressora.route.ts
  src/routes/locadora.route.ts
  src/routes/report.route.ts
  src/routes/rotinaSnmp.route.ts
  src/scripts/updatePrinterCounts.js
  src/server.ts
  src/snmp/cronJobs.ts
  src/snmp/snmpUtils.ts
  src/types/Contador.type.ts
  src/types/Impressora.type.ts
  src/types/Relatorio.type.ts
  src/types/RelatorioLocadora.type.ts
  src/types/RotinaSnmp.type.ts
  src/usecases/report/generate.pdf.ts
  src/usecases/report/generate.report.ts
  src/usecases/report/schedule.report.ts
  src/usecases/report/update.report.ts
  src/utils/sendFile.ts
  src/utils/utils.ts
  templates/report.html
  tests/controllers/Impressora.controller.spec.ts
  tests/controllers/Padrao.controller.spec.ts
  tests/controllers/Report.controller.spec.ts
  tests/controllers/RotinaSnmp.controller.test.ts
  tests/repositories/Impressora.repository.spec.ts
  tests/repositories/Report.repository.spec.ts
  tests/snmp/snmpUtils.spec.ts
  tests/usecases/generate.pdf.spec.ts
  tests/usecases/generate.report.spec.ts
  tests/utils/utils.spec.ts
  tests/validators/Impressora.validator.spec.ts
Labels: MAJOR RELEASE

#51 [HOTFIX] Erro ao gerar arquivo do relatório
  src/controllers/Report.controller.ts
Labels: hotfix

#50 [HOTFIX] Erro ao gerar arquivo do relatório
  src/controllers/Report.controller.ts
Labels: hotfix
